parameters:
    locale: 'en'
    base_url: '%env(resolve:BASE_URL)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener
            
    App\Controller\UserController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $dispatcher: '@event_dispatcher'
            
    event.jwt_created_listener:
        class: App\Event\Listener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    app.form.user:
        class: App\Form\UserType
        tags:
            - { name: form.type, alias: app_user }
            
    App\Controller\ExceptionController:
        arguments:
            $exceptionCodes: '@fos_rest.exception.codes_map'
